src/myfinance-web-dotnet-08/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet_08.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/myfinance-web-dotnet-08/Models/PlanoContaModel.cs
namespace myfinance_web_dotnet_08.Models

{
    public class PlanoContaModel
    {
        public int? Id { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
    }
} 

src/myfinance-web-dotnet-08/Models/TransacaoModel.cs
using System.ComponentModel.DataAnnotations;
using myfinance_web_dotnet_08.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_dotnet_08.Models
{
    public class TransacaoModel
    {
        public int? Id { get; set; }
        public string? Historico { get; set; }
        public string? Tipo { get; set; }
        public DateTime Data { get; set; }
        public int PlanoContaId { get; set; }
        public IEnumerable<SelectListItem>? PlanoContas { get; set; }
        public decimal Valor { get; set; }  

    }
} 

src/myfinance-web-dotnet-08/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using myfinance_web_dotnet_08.Infrastructure;
using System.Diagnostics;
using myfinance_web_dotnet_08.Models;

namespace myfinance_web_dotnet_08.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MyfinanceDbContext _context;

        public HomeController(ILogger<HomeController> logger, MyfinanceDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var nomePrimeiroPlanoConta  = _context.PlanoContas.FirstOrDefault()?.Nome;
            ViewBag.teste = nomePrimeiroPlanoConta;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult PUC()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/myfinance-web-dotnet-08/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet_08.Domain;
using myfinance_web_dotnet_08.Models;
using myfinance_web_dotnet_08.Services;
using Microsoft.Extensions.Logging;

namespace myfinance_web_dotnet_08.Controllers;

[Route("[controller]")]
public class PlanoContaController : Controller
{
        private readonly ILogger<PlanoContaController> _logger; 
        private readonly IPlanoContaService _PlanoContaService;

        public PlanoContaController(ILogger<PlanoContaController> logger, IPlanoContaService PlanoContaService)
        {
            _logger = logger;
            _PlanoContaService = PlanoContaService;
        }

        [Route("Index")]
        public ActionResult Index()
        {
            ViewBag.Lista = _PlanoContaService.ListarRegistros();
            return View();
        }

        [HttpPost]
        [HttpGet]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public ActionResult Cadastro(PlanoContaModel? model, int? id)
        {
            if (id != null && !ModelState.IsValid)
            {
                // Carregar o registro em tela para edição
                var registro = _PlanoContaService.RetornarRegistro((int)id);
                var planoContaModel = new PlanoContaModel()
                {   
                    Id = registro.Id,
                    Nome = registro.Nome,
                    Tipo = registro.Tipo
                };
                return View(planoContaModel);
            }
            else if (model != null && ModelState.IsValid)
            {
                var planoConta = new PlanoConta
                {
                    Id = model.Id ?? 0,
                    Nome = model.Nome,
                    Tipo = model.Tipo
                };
                _PlanoContaService.Salvar(planoConta);
                return RedirectToAction("Index");           
            }
            return View();  
        }
        
        [HttpGet]
        [Route("Excluir/{id}")]
        public ActionResult Excluir(int id)
        {
            _PlanoContaService.Excluir(id);
            return RedirectToAction("Index");
        }
    }       

 

src/myfinance-web-dotnet-08/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet_08.Domain;
using myfinance_web_dotnet_08.Models;
using myfinance_web_dotnet_08.Services;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_dotnet_08.Controllers;

[Route("[controller]")]
public class TransacaoController : Controller
{
    private readonly ILogger<TransacaoController> _logger;
    private readonly ITransacaoService _transacaoService;
    private readonly IPlanoContaService _planoContaService;

    public TransacaoController(ILogger<TransacaoController> logger, ITransacaoService transacaoService, IPlanoContaService planoContaService)
    {
        _logger = logger;
        _transacaoService = transacaoService;
        _planoContaService = planoContaService;
    }

    [Route("Index")]
    public IActionResult Index()
    {
        ViewBag.Lista = _transacaoService.ListarRegistros();
        return View();
    }

    [HttpPost]
    [HttpGet]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(TransacaoModel? model, int? id)
    {
        var listaPlanoContas = _planoContaService.ListarRegistros();
        var planoContaSelectItens = new SelectList(listaPlanoContas, "Id", "Nome");

        if (id != null && (!ModelState.IsValid || model?.PlanoContaId == 0))
        {
            var registro = _transacaoService.RetornarRegistro((int)id);
            var viewModel = new TransacaoModel
            {
                Id = registro.Id,
                Historico = registro.Historico,
                Tipo = registro.PlanoConta?.Tipo,
                Valor = registro.Valor,
                PlanoContaId = registro.PlanoContaId,
                PlanoContas = planoContaSelectItens
            };
            return View(viewModel);
        }
        else if (model != null && ModelState.IsValid && model.PlanoContaId != 0)
        {
            var transacao = new Transacao
            {
                Id = model.Id,
                Historico = model.Historico,
                Data = model.Data,
                Valor = model.Valor,
                PlanoContaId = model.PlanoContaId,
            };
            _transacaoService.Salvar(transacao);
            return RedirectToAction("Index");
        }
        else
        {
            var viewModel = new TransacaoModel
            {
                Data = DateTime.Now,
                PlanoContas = planoContaSelectItens
            };
            return View(viewModel);
        }
    }

    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id)
    {
        _transacaoService.Excluir(id);
        return RedirectToAction("Index");
    }
} 

src/myfinance-web-dotnet-08/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome: @ViewBag.teste</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
    

src/myfinance-web-dotnet-08/Views/Home/PUC.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome PUC</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/myfinance-web-dotnet-08/Views/PlanoConta/Cadastro.cshtml
@model PlanoContaModel
@{
    ViewData["Title"] = "Cadastro de Plano de Contas";
}
<h1>@ViewData["Title"]</h1>

<form asp-controller="PlanoConta" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id" />
            <input type="text" id="txtNome" class="form-control" asp-for="Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>@Html.RadioButtonFor(m => m.Tipo, "D") Despesa</label>
            <label>@Html.RadioButtonFor(m => m.Tipo, "R") Receita</label>
            <span asp-validation-for="Tipo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>
<script>
    function Voltar() {
        window.location.href = "../PlanoConta/Index";
    }
</script> 

src/myfinance-web-dotnet-08/Views/PlanoConta/Index.cshtml
@using myfinance_web_dotnet_08.Domain

<h1>Plano de Contas</h1>
<br />

<a type="button" class="btn btn-primary" asp-controller="PlanoConta" asp-action="Cadastro">Criar item de Plano de Conta</a>
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>
    @foreach (var item in (List<PlanoConta>)ViewBag.Lista)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nome</td>
            <td>@item.Tipo</td>
            <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
            <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
        </tr>
    }
</table>

<script>
    function Editar(id) {
        window.location.href = "../PlanoConta/Cadastro/" + id;
    }
    function Excluir(id) {
        window.location.href = "../PlanoConta/Excluir/" + id;
    }
</script> 

src/myfinance-web-dotnet-08/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet_08</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet_08.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet_08</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano de Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Registros de Transações</a>  
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - myfinance_web_dotnet_08 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/myfinance-web-dotnet-08/Views/Transacao/Cadastro.cshtml
@model myfinance_web_dotnet_08.Models.TransacaoModel
@{
    ViewData["Title"] = "Registro de Transações";
}
<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="date" class="form-control" asp-for="Data" />
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="number" step="0.01" class="form-control" asp-for="Valor" />
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Item Plano Conta</label>
            @Html.DropDownListFor(m => m.PlanoContaId, Model.PlanoContas, new { @class = "form-select" })
            <span asp-validation-for="PlanoContaId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Histórico</label>
            <input type="text" class="form-control" asp-for="Historico" />
            <span asp-validation-for="Historico" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>
<script>
    function Voltar() {
        window.location.href = "./Transacao/Index";
    }
</script> 

src/myfinance-web-dotnet-08/Views/Transacao/Index.cshtml
@using myfinance_web_dotnet_08.Domain

<h1><em>Listagem de Transações Financeiras</em></h1>
<br />
<a type="button" class="btn btn-primary" asp-controller="Transacao" asp-action="Cadastro">Registrar uma Transação</a>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Histórico</th>
        <th>Tipo</th>
        <th>Valor</th>
        <th>Data</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in (List<Transacao>)ViewBag.Lista)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Historico</td>
            <td>@item.PlanoConta?.Tipo</td>
            <td>@item.Valor</td>
            <td>@item.Data</td>
            <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
            <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
        </tr>
    }
</table>
<script>
    function Editar(id) {
        window.location.href = "../Transacao/Cadastro/" + id;
    }
    function Excluir(id) {
        window.location.href = "../Transacao/Excluir/" + id;
    }
</script> 